### ISSUE TITLE
1password.com is not considered a valid domain

### ISSUE THREAD

**Issue by stayallive** [thephpleague/uri-parser#10]
## Issue summary

1password.com is not considered a valid domain throwing a `League\Uri\Exception`.

`The submitted uri 1password.com contains an invalid path`

This _does_ follow RFC3986 correctly AFAIK but since this domain is registerable it should be validated correctly by this library IMHO.

### System informations

| Information | Description |
|--------------|---------|
| league-uri-parser version | master |
| PHP/HHVM version | 7.1.8 |
| OS Platform | OS X 10.13.2 |

## Standalone code, or other way to reproduce the problem

```php
$parser = new UriParser();
$parser('1password.com');
```

### Expected result

1password.com is validated as a valid domain with `1password.com` as the host.

```php
Array &0 (
    'scheme' => null
    'user' => null
    'pass' => null
    'host' => '1password.com'
    'port' => null
    'path' => null
    'query' => null
    'fragment' => null
)
```

### Actual result

`League\Uri\Exception`: The submitted uri 1password.com contains an invalid path

```php
Array &0 (
    'scheme' => null
    'user' => null
    'pass' => null
    'host' => null
    'port' => null
    'path' => 'password.com'
    'query' => null
    'fragment' => null
)
```

### Test output

```php
1) LeagueTest\Uri\Parser\ParserTest::testParseSucced with data set "URI starting with number" ('password.com', array(null, null, null, '1password.com', null, '', null, null))
Failed asserting that Array &0 (
    'scheme' => null
    'user' => null
    'pass' => null
    'host' => null
    'port' => null
    'path' => 'password.com'
    'query' => null
    'fragment' => null
) is identical to Array &0 (
    'scheme' => null
    'user' => null
    'pass' => null
    'host' => '1password.com'
    'port' => null
    'path' => ''
    'query' => null
    'fragment' => null
).
```

**Comment by nyamsprod** [comment]
I don't know why you are getting a Exception but I do now why the expected Uri is not the one your get 👍 
Please read this https://github.com/thephpleague/uri/issues/56

**Comment by stayallive** [comment]
I see, well changing it to `https://1password.com` does fix it for me. So that works for me 👍 

```php
        //No scheme is present so we ensure that the path respects RFC3986
        if (false !== ($pos = strpos($uri, ':')) && false === strpos(substr($uri, 0, $pos), '/')) {
            throw Exception::createFromInvalidPath($uri);
        }
```

It might be that the path expects a `/` (which is not present since the host is seen as the path here).
