### ISSUE TITLE
Port ranges

### ISSUE THREAD

**Issue by kelunik** [thephpleague/uri-parser#15]
The RFC doesn't define any valid port range, which means any port is valid, also ports outside the range of TCP / UDP. Currently ports are limited to 1-65535.

**Comment by nyamsprod** [comment]
Indeed you are correct. I overlooked this one because at the time I was trying to make my lib PSR-7 compliant too. since we are improving the parser we can remove this limitation and just put a regexp to match numeric string.

**Comment by nyamsprod** [comment]
this issue is resolved on the master branch
