### ISSUE TITLE
Make ext-intl optional

### ISSUE THREAD

**Issue by kelunik** [thephpleague/uri-parser#16]
I think with the latest changes we can make `ext-intl` optional. If it's available, keep the current code. If not, just error on IDNs.

**Comment by kelunik** [comment]
@nyamsprod Yes, similar to what we do [here](https://github.com/amphp/uri/blob/b857ba4df3cf0852302ba1637fccce4ce1205241/src/functions.php#L33-L46). Just noticed that that code doesn't even use `strtolower`…

**Comment by nyamsprod** [comment]
ok understood... the parser does not use `strtolower` either 👍 , the URI scheme uses it because it normalizes the output to lowercase.

**Comment by kelunik** [comment]
@nyamsprod Yes, it's completely fine for the parser, but `amphp/uri` calls that method `normalize*` and that's what it should do. ;-)

**Comment by nyamsprod** [comment]
@kelunik I've added [this](https://github.com/thephpleague/uri-parser/blob/master/src/Parser.php#L400-L412) I believe this should resolve the issue.

**Comment by kelunik** [comment]
@nyamsprod Yes, looks fine. Should we introduce a special exception for that?

**Comment by nyamsprod** [comment]
Maybe something along the line of:

```php
class MissingIDNASupport extends \RuntimeException
{
}
```

Since the error as nothing to do with the parser per se ?

**Comment by kelunik** [comment]
I think it should extend the `Exception` class already present, so you don't have to catch it separately if you don't care. I'm personally more used to the `MissingIdnSupport` casing, but that's up to you.

**Comment by nyamsprod** [comment]
>I think it should extend the Exception class already present, so you don't have to catch it separately if you don't care. 

Agreed about extending the `Exception` class

I'm trying to follow this convention https://wiki.php.net/rfc/class-naming so IDN in uppercase unless I've read it wrong. 

I'll add the Exception then will leave everything as it is for a day a two ... review and then release 👍

**Comment by kelunik** [comment]
Actually I voted for _"PascalCase except Acronyms"_ there, but against the RFC overall. :smile:

**Comment by nyamsprod** [comment]
@kelunik since in all the packages I went with `Uri` and not `URI` let's stay coherent .. so I went with `MissingIdnSupport ` :+1:

**Comment by kelunik** [comment]
@nyamsprod We should probably rename the `IDNA` error method, too.

**Comment by nyamsprod** [comment]
Indeed I'll update the method name is other packages
