### ISSUE TITLE
The parser does not respect RFC3986 for non-leading digits inside scheme

### ISSUE THREAD

**Issue by mudhoney** [thephpleague/uri-parser#18]
## Issue summary

The parser does not fully comply with the RFC3986. As mentioned in the [section 3.1](https://tools.ietf.org/html/rfc3986#section-3.1).

> followed by any combination of letters, digits

### System informations

| Information | Description |
|--------------|---------|
| league-uri-parser version | 1.4.0  |
| PHP/HHVM version | 7.2.9  |
| OS Platform | all |

## Standalone code, or other way to reproduce the problem
```
var_export((new Parser())('s3://somebucket/somefile.txt'));
```
### Expected result
```
array (
  'scheme' => 's3',
  'user' => NULL,
  'pass' => NULL,
  'host' => 'somebucket',
  'port' => NULL,
  'path' => '/somefile.txt',
  'query' => NULL,
  'fragment' => NULL,
)
```

### Actual result
```
Uncaught League\Uri\Exception: The submitted uri `s3://somebucket/somefile.txt` contains an invalid path
```

**Comment by nyamsprod** [comment]
version 1.4.1 is out with your bugfix .. thanks for the contribution

**Comment by mudhoney** [comment]
Happy to help , thank you for the quick release :)
