### ISSUE TITLE
Improve League URI Parser speed

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/uri-parser#2]
## Issue summary

The current parser is accurate but slow. We should try to improve the parser speed.

**Comment by pierrejoye** [comment]
Looks like repetitive patterns for all various preg call. Could be done in the 1st one.

Also I would suggest to enable pcre JIT when available.

Simple regex (host f.e.) could be faster using simple strings ops.

After quick review, but analyze the pcre calls will bring more insight.

**Comment by Giuseppe-Mazzapica** [comment]
Add same idea of @pierrejoye: the parsing should be done with a single, bigger, `preg_match` and sometimes no need regex at all.

For example

```php
if (preg_match(self::REGEXP_INVALID_URI_CHAR, $uri)) {
  throw new InvalidArgumentException();
}
```

could be

```php
if ($uri !== str_replace(self::INVALID_URI_CHARS, 'x', $uri)) {
  throw new InvalidArgumentException();
}
```

where

```php
const INVALID_URI_CHARS = [
		"\x00",
		"\x01",
		"\x02",
		"\x03",
		"\x04",
		"\x05",
		"\x06",
		"\x07",
		"\x08",
		"\x09",
		"\x0A",
		"\x0B",
		"\x0C",
		"\x0D",
		"\x0E",
		"\x0F",
		"\x10",
		"\x11",
		"\x12",
		"\x13",
		"\x14",
		"\x15",
		"\x16",
		"\x17",
		"\x18",
		"\x19",
		"\x1A",
		"\x1B",
		"\x1C",
		"\x1D",
		"\x1E",
		"\x1F",
		"\x7F",
	];
```

**Comment by frederikbosch** [comment]
You might want to consider looking at other implementations. The first thing that comes up in my mind in Servo (Mozilla

**Comment by nyamsprod** [comment]
Improvement so far:

@pierrejoye Only 3 regular expressions remains. And one won't be used [in PHP7 in most cases](https://github.com/thephpleague/uri-parser/blob/master/src/Parser.php#L46)

@Giuseppe-Mazzapica instead of `str_replace` I'm using `strcspn` [to check for invalid characters](https://github.com/thephpleague/uri-parser/blob/master/src/Parser.php#L88)

**Comment by Giuseppe-Mazzapica** [comment]
@nyamsprod I used `str_replace` to have invalid chars in array which is more readable, but I guess `strcspn` is fine :)

Have you noted speed improvements so far?

**Comment by nyamsprod** [comment]
yes great improvement. The Parser on the master branch compared to [the original parser found on league URI v4](https://github.com/thephpleague/uri/blob/master/src/UriParser.php) there's a gain between 30 and 75% depending on the complexity of the URI structure.

**Comment by nyamsprod** [comment]
version 0.2.0 is out which removes all regular expressions. The parser speed is improved between 30 and 75% against the current stable League\Uri\UriParser.
