### ISSUE TITLE
why not use League\Uri\Uri

### ISSUE THREAD

**Issue by aogg** [thephpleague/uri-parser#22]
use League\Uri\Components\Query;
use League\Uri\Uri;
use League\Uri\UriModifier;

$uri = Uri::createFromString('http://example.com?q=value#fragment');
$newUri = UriModifier::appendQuery($uri, 'q=new.Value');
echo $newUri; // 'http://example.com?q=value&q=new.Value#fragment';

$query = Query::createFromUri($newUri);
$query->get('q');    // returns 'value'
$query->getAll('q'); // returns ['value', 'new.Value']
$query->params('q'); // returns 'new.Value'

**Comment by aogg** [comment]
composer require league/uri-parser

**Comment by aogg** [comment]
The right way 

composer require league/uri

**Comment by nyamsprod** [comment]
@aogg if you read the documentation (https://uri.thephpleague.com) you will see clearly noted that this package should be avoided for any new project as `League\uri` is now the correct library to use.
