### ISSUE TITLE
The parser does not respect RFC3986 for scheme parsing

### ISSUE THREAD

**Issue by Baptouuuu** [thephpleague/uri-parser#3]
## Issue summary

The parser does not fully comply with the RFC3986. As mentioned in the section [`3.1. Scheme`](https://tools.ietf.org/html/rfc3986#section-3.1) the `-` (hyphen) character is a valid one for a scheme.

### System informations

| Information | Description |
|--------------|---------|
| league-uri-parser version | 1.0 |
| PHP/HHVM version | >=7.0.0 |
| OS Platform | all |

## Standalone code, or other way to reproduce the problem

```php
(new Parser)('android-app://org.wikipedia/http/en.m.wikipedia.org/wiki/The_Hitchhiker%27s_Guide_to_the_Galaxy')
```

### Expected result

```php
[
    'scheme' => 'android-app',
    'user' => null,
    'pass' => null,
    'host' => 'org.wikipedia',
    'port' => null,
    'path' => '/http/en.m.wikipedia.org/wiki/The_Hitchhiker%27s_Guide_to_the_Galaxy',
    'query' => null,
    'fragment' => null,
]
```

### Actual result

```
League\Uri\Exception: The submitted uri `android-app://org.wikipedia/http/en.m.wikipedia.org/wiki/The_Hitchhiker%27s_Guide_to_the_Galaxy` contains an invalid path
```

**Comment by nyamsprod** [comment]
@Baptouuuu good catch this was an oversight from my part 👍

**Comment by Baptouuuu** [comment]
Glad to help :)

**Comment by nyamsprod** [comment]
1.0.4 is released
