### ISSUE TITLE
improve Parser::isHost Host validation

### ISSUE THREAD

**Issue by idealogica** [thephpleague/uri-parser#5]
## Issue summary

Http::createFromString('https://r5---sn-h0jeen7y.domain.com') throws the exception.
`Fatal error: Uncaught League\Uri\Exception: The submitted host `r5---sn-h0jeen7y.domain.com` is invalid`

### System informations

| Information | Description |
|--------------|---------|
| league-uri-parser version | 1.0.4  |
| PHP/HHVM version | 7.1.1 |
| OS Platform | Ubuntu |

## Standalone code, or other way to reproduce the problem

Http::createFromString('https://r5---sn-h0jeen7y.domain.com');

### Expected result

Should return Http instance.

### Actual result

Throws the exception.

**Comment by nyamsprod** [comment]
@idealogica thanks for reporting this bug a fix has been push. Could you review the fix please. If it is ok, I'll merge it to the master and release a patch ASAP. :+1:

**Comment by nyamsprod** [comment]
This bug is fixed on the master branch and will be released in the next patch release

**Comment by idealogica** [comment]
Hello! I checked and confirm that bug was fixed. Thanks for fixing and for the awesome package :)

**Comment by nyamsprod** [comment]
you can make a composer update you'll get the new version which is now released
