### ISSUE TITLE
Invalid submitted host due to double dashes

### ISSUE THREAD

**Issue by rbairwell** [thephpleague/uri-parser#7]
## Issue summary

Valid domains with double dashes in second position are rejected as "The submitted host ... is invalid"

Known valid, registered, domain names:
[tw--services.co.uk](https://www.nominet.uk/whois/?query=tw--services.co.uk#whois-results) (registered February 2017)
[om--tat-sat.co.uk](https://www.nominet.uk/whois/?query=om--tat-sat.co.uk#whois-results) (registered September 1999)
(also pr--newswire.co.uk )
### System informations

| Information | Description |
|--------------|---------|
| league-uri-parser version | 1.0.4  |
| PHP/HHVM version | 7.1.6  |
| OS Platform | Linux [Devilbox Docker](https://github.com/cytopia/devilbox)  |

## Standalone code, or other way to reproduce the problem

```php
<?php
use League\Uri\Parser;

include 'vendor/autoload.php';
print 'PHP: '.PHP_VERSION.' on '.php_uname().PHP_EOL;
$parser = new Parser();
$domains=['example.co.uk','tw--services.co.uk','om--tat-sat.co.uk'];
foreach ($domains as $domain) {
    try {
        $out=$parser('http://'.$domain);
        print 'Parsed: '.$out['host'].PHP_EOL;
    } catch (\Throwable $e) {
        print 'Exception: '.$e->getMessage().PHP_EOL;
    }
}
```

### Expected result
```
PHP: 7.1.6 on Linux 1dc77c140617 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64
Parsed: example.co.uk
Parsed: tw--services.co.uk
Parsed: om--tat-sat.co.uk
```
### Actual result
```
PHP: 7.1.6 on Linux 1dc77c140617 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64
Parsed: example.co.uk
Exception: The submitted host `tw--services.co.uk` is invalid
Exception: The submitted host `om--tat-sat.co.uk` is invalid
```

**Comment by nyamsprod** [comment]
to be honest I've copy/paste your code and I have no error. I've updated the code to be more clear but I failed to reproduce it even when adding your code to the test suite

**Comment by nyamsprod** [comment]
here's the results on https://3v4l.org/dBZbR  no error spotted

**Comment by rbairwell** [comment]
Thank you. Seems my composer.json had 1.0.4 hard set and the bug doesn't surface in 1.0.5 (and this actually now appears to be a duplicate of #5).

Sorry about wasting your time on this issue: I should have cross checked earlier - I blame a long day.
